### ISSUE TITLE
Code probs!

### ISSUE THREAD

**Issue by Enaisreal2401** [RhenaudTheLukark/CreateYourKris#17]
Hey, I tried to make Noelle in CYK, but for some reason, the code is wrong! IDK if I'm just an Idiot, or the game is. (Most likely, it's me) anyway, I put the Lua in, And I will type out the error message! (FYI, I checked the two other encounters, and It only didn't work when I added Noelle as a player) If you have questions about anything specific about my code, just ask. I am known to not be completely specific about many things.

error in script Jarek (Jarek is the Encounter name)

Lua/Players/Noelle.lua:(line 23, char 11-12): unexpected symbol near '='

[Noelle.zip](https://github.com/RhenaudTheLukark/CreateYourKris/files/7592323/Noelle.zip)

- Sorry if I'm being a nuisance!
-Jarek

**Comment by RhenaudTheLukark** [comment]
I'm afraid that error comes from you: you closed the `animations` table at the end of line 22, but it should be closed later, as all following lines are also in that table.

Also, please, in the future, try to join the [Discord server](https://discord.gg/0c8fN7KCwBh4ZBL9) or the [subreddit](https://www.reddit.com/r/Unitale) and ask about that kind of thing there, it'll be easier to help you on another platform!

**Comment by Enaisreal2401** [comment]
Oh, ok Thanks! I'll do just that if I have any more problems!
