### ISSUE TITLE
Bug when trying to attack the enemy

### ISSUE THREAD

**Issue by ratmoney** [RhenaudTheLukark/CreateYourKris#19]
When I'm trying to just attack the enemy, the game crashes and gives me this error message.

"error in script Example

C:/Users/Owner/Downloads/CYF/Mods/CreateYourKris-1.1.1/Lua/Libraries/CYK/Animation.Lua:(line 57, char 45-174): cannot access field faceSprite of userdata<LuaPlayerUI>

Press ESC to reload"

I'm really bad at code and stuff, so if I should include anything else, please tell me.

**Comment by RhenaudTheLukark** [comment]
You must have downloaded the latest release. Please download the current verson instead to get that error fixed!

**Comment by ratmoney** [comment]
Thank you, I goofed up, it's working now. Lmao
